"""initial schema

Revision ID: dd7ff4170ded
Revises: 
Create Date: 2026-05-12 21:45:30.491861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd7ff4170ded'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_codigo'), 'material', ['codigo'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('workorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_orden', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pendiente', 'surtido', 'en_proceso', 'finalizado', name='workorderstatus'), nullable=False),
    sa.Column('cantidad_a_producir', sa.Float(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workorder_numero_orden'), 'workorder', ['numero_orden'], unique=True)
    op.create_table('finishedproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lote_produccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cantidad_producida', sa.Float(), nullable=False),
    sa.Column('cantidad_disponible', sa.Float(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['workorder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finishedproduct_codigo'), 'finishedproduct', ['codigo'], unique=True)
    op.create_index(op.f('ix_finishedproduct_lote_produccion'), 'finishedproduct', ['lote_produccion'], unique=False)
    op.create_table('materiallot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('cantidad_reservada', sa.Float(), nullable=False),
    sa.Column('fecha_entrada', sa.DateTime(), nullable=False),
    sa.Column('fecha_caducidad', sa.DateTime(), nullable=True),
    sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'codigo_lote', name='uq_material_lote_codigo')
    )
    op.create_index(op.f('ix_materiallot_codigo_lote'), 'materiallot', ['codigo_lote'], unique=False)
    op.create_index(op.f('ix_materiallot_fecha_entrada'), 'materiallot', ['fecha_entrada'], unique=False)
    op.create_table('workorderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_requerida', sa.Float(), nullable=False),
    sa.Column('cantidad_asignada', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['workorder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finishedproductshipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finished_product_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('destinatario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('documento_envio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finished_product_id'], ['finishedproduct.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventorymovement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('movement_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('material_lot_id', sa.Integer(), nullable=True),
    sa.Column('finished_product_id', sa.Integer(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reference_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finished_product_id'], ['finishedproduct.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['material_lot_id'], ['materiallot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['workorder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventorymovement_inventory_type'), 'inventorymovement', ['inventory_type'], unique=False)
    op.create_index(op.f('ix_inventorymovement_movement_type'), 'inventorymovement', ['movement_type'], unique=False)
    op.create_table('workorderitemlotallocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_item_id', sa.Integer(), nullable=False),
    sa.Column('material_lot_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_lot_id'], ['materiallot.id'], ),
    sa.ForeignKeyConstraint(['work_order_item_id'], ['workorderitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workorderitemlotallocation')
    op.drop_index(op.f('ix_inventorymovement_movement_type'), table_name='inventorymovement')
    op.drop_index(op.f('ix_inventorymovement_inventory_type'), table_name='inventorymovement')
    op.drop_table('inventorymovement')
    op.drop_table('finishedproductshipment')
    op.drop_table('workorderitem')
    op.drop_index(op.f('ix_materiallot_fecha_entrada'), table_name='materiallot')
    op.drop_index(op.f('ix_materiallot_codigo_lote'), table_name='materiallot')
    op.drop_table('materiallot')
    op.drop_index(op.f('ix_finishedproduct_lote_produccion'), table_name='finishedproduct')
    op.drop_index(op.f('ix_finishedproduct_codigo'), table_name='finishedproduct')
    op.drop_table('finishedproduct')
    op.drop_index(op.f('ix_workorder_numero_orden'), table_name='workorder')
    op.drop_table('workorder')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_material_codigo'), table_name='material')
    op.drop_table('material')
    # ### end Alembic commands ###
